// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld2.proto

package com.springboot.rpc.bid;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.springboot.rpc.bid.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
