// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld1.proto

package com.springboot.rpc.async;

public interface HelloMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.springboot.rpc.async.HelloMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
