// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.springboot.rpc.loadbalance;

public interface HelloMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.springboot.rpc.loadbalance.HelloMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
