spring:
  datasource:
    driver-class-name: com.taosdata.jdbc.TSDBDriver
    url: jdbc:TAOS://192.168.87.139:6030/demo?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
    username: root
    password: taosdata
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20


logging:
  level:
    com:
      taosdata:
        example:
          mybatisplusdemo:
            mapper: debug


##mybatis.mapper-locations=classpath:mapper/*.xml
